//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinkoFormulaDictionary
    {
        public PinkoFormulaDictionary()
        {
            this.PinkoFormulas = new HashSet<PinkoFormula>();
        }
    
        public string Id { get; set; }
    
        public virtual ICollection<PinkoFormula> PinkoFormulas { get; set; }
    }
}
