//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinkoFormula
    {
        public string Id { get; set; }
        public string IdType { get; set; }
        public string IdName { get; set; }
        public string FieldName { get; set; }
        public string Source { get; set; }
        public string PinkoFormulaDictionaryId { get; set; }
    
        public virtual PinkoFormulaDictionary PinkoFormulaDictionary { get; set; }
    }
}
