//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkDao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PinkoEntitiesContainer : DbContext
    {
        public PinkoEntitiesContainer()
            : base("name=PinkoEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PinkoFormula> PinkoFormulas { get; set; }
        public DbSet<PinkoFormulaDictionary> PinkoFormulaDictionaries { get; set; }
        public DbSet<EntitytFormulaExpression> EntitytFormulaExpressions { get; set; }
    }
}
